version: "3.3"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    environment:
      SWAGGER_FILE: /tmp/swagger.yaml
    volumes:
    - ./src/swagger:/tmp
    ports:
      - "8081:8080"
  proffy-db:
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password
    container_name: proffy_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: proffy
    ports:
      - "3306:3306"
    volumes:
      - my-db/:/var/lib/mysql
volumes:
  my-db:


