version: '3.7'

services:
  proffy-server:
    container_name: proffy-server
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: npm run start:dev
    networks:
      - webnet
    depends_on:
      - proffy_db
  proffy_db:
    container_name: proffy_db
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: proffy
    ports:
      - 3306:3306
    volumes:
      - my-db/:/var/lib/mysql
networks:
  webnet:
volumes:
  my-db:
